# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

#I use a development account on auth0.
development:
  secret_key_base: 18451581609752ad653f43e9214e87978cf06fdc04daebad9faa2daf9023f4a892efe61a1448b559c55ae343841b5aa873c36478e325c44d9ef0a2c61682e50d
  auth0_client_id: X0m2PZEyAOqhtLY1Qz9mdetHzQcDsG8U
  auth0_client_secret: B9cx35Lqlejy2ORT2wR-qKVcXCaJEv41enflXTMxUUl383WpEFbwT18IdguGIuw7
  auth0_api_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJUWnBQRXp5eWpQbTN2VmdSdU9yQjJTakRTVnhFdnJiSCIsInNjb3BlcyI6eyJ1c2VycyI6eyJhY3Rpb25zIjpbInJlYWQiXX19LCJpYXQiOjE0NDk4OTM2OTMsImp0aSI6IjJhNjJiNDJmY2IyODE5ZmJhN2EzNWE1NDNkYmIyMDZiIn0.Kcq6ipqAk63JujvXuPnAnMwfxZ2C8DMCk-JWehGfSEc
  auth0_api_domain: guesstimate-development.auth0.com
  algolia_application_id: M629R9UGSG
  algolia_api_key: 6801f2d2f73fe7364696ad43fc65689c

test:
  secret_key_base: d3a6ebb279e62140007529b48c9d302013e884a6e8039eb731642fce9b0c2d606d8eb349ea084e01ad388a54adc610823ed89119c8a6d8cc0a7289bde27cbbd2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  auth0_client_id: <%= ENV["AUTH0_CLIENT_ID"] %>
  auth0_client_secret: <%= ENV["AUTH0_CLIENT_SECRET"] %>
  auth0_api_token: <%= ENV["AUTH0_API_TOKEN"] %>
  auth0_api_domain: <%= ENV["AUTH0_API_DOMAIN"] %>
  algolia_appliation_id: M629R9UGSG
  algolia_api_key: <%= ENV["ALGOLIA_API_KEY"] %>
